#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("WeatherApp.Resource", IsApplication=true)]

namespace WeatherApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::WeatherApp.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::WeatherApp.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::WeatherApp.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::WeatherApp.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::WeatherApp.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::WeatherApp.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::WeatherApp.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::WeatherApp.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::WeatherApp.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::WeatherApp.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::WeatherApp.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::WeatherApp.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::WeatherApp.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::WeatherApp.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::WeatherApp.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::WeatherApp.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::WeatherApp.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::WeatherApp.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::WeatherApp.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::WeatherApp.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::WeatherApp.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::WeatherApp.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::WeatherApp.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::WeatherApp.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::WeatherApp.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::WeatherApp.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::WeatherApp.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::WeatherApp.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::WeatherApp.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::WeatherApp.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::WeatherApp.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::WeatherApp.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::WeatherApp.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::WeatherApp.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::WeatherApp.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::WeatherApp.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::WeatherApp.Resource.Styleable.ProgressWheel_ahTextSize;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int ahBarColor = 2130771971;
			
			// aapt resource value: 0x7f01000b
			public const int ahBarLength = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int ahBarWidth = 2130771978;
			
			// aapt resource value: 0x7f010008
			public const int ahCircleColor = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int ahDelayMillis = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int ahRadius = 2130771977;
			
			// aapt resource value: 0x7f010004
			public const int ahRimColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int ahRimWidth = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int ahSpinSpeed = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int ahText = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int ahTextColor = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int ahTextSize = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int TransGray = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ClearDay = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int few_clouds = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Forecast = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_errorstatus = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_successstatus = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int Icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int Mist = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int QuestionMark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int rain = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int roundedbg = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int roundedbgdark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int scattered_clouds = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Snow = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Splash = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int SplashLogo = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Storm = 2130837520;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06003a
			public const int btnAuckland = 2131099706;
			
			// aapt resource value: 0x7f060037
			public const int btnCelsius = 2131099703;
			
			// aapt resource value: 0x7f06003d
			public const int btnChrist = 2131099709;
			
			// aapt resource value: 0x7f060038
			public const int btnFaren = 2131099704;
			
			// aapt resource value: 0x7f06002a
			public const int btnForecast = 2131099690;
			
			// aapt resource value: 0x7f06003b
			public const int btnHamilton = 2131099707;
			
			// aapt resource value: 0x7f06002b
			public const int btnHelp = 2131099691;
			
			// aapt resource value: 0x7f060039
			public const int btnTrackGPS = 2131099705;
			
			// aapt resource value: 0x7f06003c
			public const int btnWellington = 2131099708;
			
			// aapt resource value: 0x7f06003e
			public const int imageView1 = 2131099710;
			
			// aapt resource value: 0x7f060003
			public const int imgCurrIcon = 2131099651;
			
			// aapt resource value: 0x7f06002d
			public const int imgIcon = 2131099693;
			
			// aapt resource value: 0x7f06000d
			public const int imgWeather1 = 2131099661;
			
			// aapt resource value: 0x7f060012
			public const int imgWeather2 = 2131099666;
			
			// aapt resource value: 0x7f060017
			public const int imgWeather3 = 2131099671;
			
			// aapt resource value: 0x7f06001c
			public const int imgWeather4 = 2131099676;
			
			// aapt resource value: 0x7f060021
			public const int imgWeather5 = 2131099681;
			
			// aapt resource value: 0x7f060032
			public const int lblCityName = 2131099698;
			
			// aapt resource value: 0x7f060007
			public const int lblCurrCity = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int lblCurrDate = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int lblCurrTime = 2131099654;
			
			// aapt resource value: 0x7f06002e
			public const int lblDate = 2131099694;
			
			// aapt resource value: 0x7f06000c
			public const int lblDate1 = 2131099660;
			
			// aapt resource value: 0x7f060011
			public const int lblDate2 = 2131099665;
			
			// aapt resource value: 0x7f060016
			public const int lblDate3 = 2131099670;
			
			// aapt resource value: 0x7f06001b
			public const int lblDate4 = 2131099675;
			
			// aapt resource value: 0x7f060020
			public const int lblDate5 = 2131099680;
			
			// aapt resource value: 0x7f060034
			public const int lblFeels = 2131099700;
			
			// aapt resource value: 0x7f06000f
			public const int lblHighTemp1 = 2131099663;
			
			// aapt resource value: 0x7f060014
			public const int lblHighTemp2 = 2131099668;
			
			// aapt resource value: 0x7f060019
			public const int lblHighTemp3 = 2131099673;
			
			// aapt resource value: 0x7f06001e
			public const int lblHighTemp4 = 2131099678;
			
			// aapt resource value: 0x7f060023
			public const int lblHighTemp5 = 2131099683;
			
			// aapt resource value: 0x7f060033
			public const int lblHumidity = 2131099699;
			
			// aapt resource value: 0x7f06000e
			public const int lblLowTemp1 = 2131099662;
			
			// aapt resource value: 0x7f060013
			public const int lblLowTemp2 = 2131099667;
			
			// aapt resource value: 0x7f060018
			public const int lblLowTemp3 = 2131099672;
			
			// aapt resource value: 0x7f06001d
			public const int lblLowTemp4 = 2131099677;
			
			// aapt resource value: 0x7f060022
			public const int lblLowTemp5 = 2131099682;
			
			// aapt resource value: 0x7f060036
			public const int lblMeasurements = 2131099702;
			
			// aapt resource value: 0x7f06000b
			public const int lblNameDay1 = 2131099659;
			
			// aapt resource value: 0x7f060010
			public const int lblNameDay2 = 2131099664;
			
			// aapt resource value: 0x7f060015
			public const int lblNameDay3 = 2131099669;
			
			// aapt resource value: 0x7f06001a
			public const int lblNameDay4 = 2131099674;
			
			// aapt resource value: 0x7f06001f
			public const int lblNameDay5 = 2131099679;
			
			// aapt resource value: 0x7f060031
			public const int lblTemp = 2131099697;
			
			// aapt resource value: 0x7f06002f
			public const int lblTime = 2131099695;
			
			// aapt resource value: 0x7f060035
			public const int lblWeatherCond = 2131099701;
			
			// aapt resource value: 0x7f06002c
			public const int linearLayout1 = 2131099692;
			
			// aapt resource value: 0x7f060030
			public const int linearLayout2 = 2131099696;
			
			// aapt resource value: 0x7f060002
			public const int linearLayout3 = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int linearLayout4 = 2131099652;
			
			// aapt resource value: 0x7f06000a
			public const int linearLayout5 = 2131099658;
			
			// aapt resource value: 0x7f060009
			public const int linearLayout6 = 2131099657;
			
			// aapt resource value: 0x7f060024
			public const int linearLayout7 = 2131099684;
			
			// aapt resource value: 0x7f060008
			public const int linearLayout8 = 2131099656;
			
			// aapt resource value: 0x7f060001
			public const int linearLayout9 = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int lnBackground = 2131099648;
			
			// aapt resource value: 0x7f060029
			public const int lnGrayColor = 2131099689;
			
			// aapt resource value: 0x7f060027
			public const int loadingImage = 2131099687;
			
			// aapt resource value: 0x7f060025
			public const int loadingProgressBar = 2131099685;
			
			// aapt resource value: 0x7f060028
			public const int loadingProgressWheel = 2131099688;
			
			// aapt resource value: 0x7f060026
			public const int textViewStatus = 2131099686;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Forecast = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int loading = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int loadingimage = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int loadingprogress = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Main = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Options = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int SplashScreen = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int Measurements = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int WeatherCond = 2130968579;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int strFeelsLike = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int strHumidity = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ProgressWheel = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
