#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("JazzyViewPagerSample.Resource", IsApplication=true)]

namespace JazzyViewPagerSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Jazzy.Resource.Attribute.outlineColor = global::JazzyViewPagerSample.Resource.Attribute.outlineColor;
			global::Jazzy.Resource.Attribute.outlineEnabled = global::JazzyViewPagerSample.Resource.Attribute.outlineEnabled;
			global::Jazzy.Resource.Color.holo_blue = global::JazzyViewPagerSample.Resource.Color.holo_blue;
			global::Jazzy.Resource.Styleable.JazzyViewPager = global::JazzyViewPagerSample.Resource.Styleable.JazzyViewPager;
			global::Jazzy.Resource.Styleable.JazzyViewPager_outlineColor = global::JazzyViewPagerSample.Resource.Styleable.JazzyViewPager_outlineColor;
			global::Jazzy.Resource.Styleable.JazzyViewPager_outlineEnabled = global::JazzyViewPagerSample.Resource.Styleable.JazzyViewPager_outlineEnabled;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int jazzy_effects = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010001
			public const int outlineColor = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int outlineEnabled = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int holo_blue = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int jazzy = 2131230720;
			
			// aapt resource value: 0x7f08000c
			public const int menu_accordian = 2131230732;
			
			// aapt resource value: 0x7f080003
			public const int menu_cube_in = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int menu_cube_out = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int menu_flip_horizontal = 2131230726;
			
			// aapt resource value: 0x7f080005
			public const int menu_flip_vertical = 2131230725;
			
			// aapt resource value: 0x7f08000b
			public const int menu_rotate_down = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int menu_rotate_up = 2131230730;
			
			// aapt resource value: 0x7f080007
			public const int menu_stack = 2131230727;
			
			// aapt resource value: 0x7f080001
			public const int menu_standard = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int menu_tablet = 2131230722;
			
			// aapt resource value: 0x7f080008
			public const int menu_zoom_in = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int menu_zoom_out = 2131230729;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int MainMenu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] JazzyViewPager = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 1
			public const int JazzyViewPager_outlineColor = 1;
			
			// aapt resource value: 0
			public const int JazzyViewPager_outlineEnabled = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
